import fs from "fs"
import path from "path"

const REGISTRY_DIR = path.join(process.cwd(), "src/registry/editor")
const OUTPUT_FILE = path.join(REGISTRY_DIR, "editor.d.ts")

function extractActionKeys(): string[] {
  const keys = new Set<string>()
  const files = fs.readdirSync(REGISTRY_DIR)

  for (const file of files) {
    if (!file.endsWith(".tsx") || file === "editor.tsx") continue

    const filePath = path.join(REGISTRY_DIR, file)
    const content = fs.readFileSync(filePath, "utf-8")

    // Match key: "..." patterns in command definitions
    const keyPattern = /key:\s*["']([^"']+)["']/g
    let match

    while ((match = keyPattern.exec(content)) !== null) {
      keys.add(match[1])
    }
  }

  return Array.from(keys).sort()
}

function generateTypes(keys: string[]): string {
  const keyUnion = keys.map((k) => `  | "${k}"`).join("\n")

  return `// Auto-generated by scripts/generate-editor-types.ts
// Do not edit manually - regenerate with: pnpm run editor:types

/**
 * Union type of all registered editor action keys.
 * Used for autocomplete in EditorButton and EditorDropdown components.
 */
export type EditorActionKey =
${keyUnion}
`
}

function main() {
  console.log("Generating editor action types...")

  const keys = extractActionKeys()
  console.log(`Found ${keys.length} action keys:`, keys)

  const typeContent = generateTypes(keys)
  fs.writeFileSync(OUTPUT_FILE, typeContent)

  console.log(`Generated ${OUTPUT_FILE}`)
}

main()
